SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS `clase` ;
CREATE SCHEMA IF NOT EXISTS `clase` DEFAULT CHARACTER SET latin1 ;
USE `clase` ;

-- -----------------------------------------------------
-- Table `PERSONAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PERSONAS` ;

CREATE  TABLE IF NOT EXISTS `PERSONAS` (
  `ID_PERSONA` BIGINT(20) NOT NULL ,
  `APELLIDOS` VARCHAR(56) NOT NULL ,
  `NOMBRE` VARCHAR(24) NOT NULL ,
  PRIMARY KEY (`ID_PERSONA`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CLASES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLASES` ;

CREATE  TABLE IF NOT EXISTS `CLASES` (
  `ID_CLASE` BIGINT(20) NOT NULL AUTO_INCREMENT ,
  `DENOMINACION` VARCHAR(8) NOT NULL ,
  PRIMARY KEY (`ID_CLASE`) )
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ALUMNOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ALUMNOS` ;

CREATE  TABLE IF NOT EXISTS `ALUMNOS` (
  `ID_PERSONA` BIGINT(20) NOT NULL ,
  `ID_CLASE` BIGINT(20) NULL DEFAULT NULL ,
  PRIMARY KEY (`ID_PERSONA`) ,
  CONSTRAINT `FK_ALUMNOS_ID_PERSONA`
    FOREIGN KEY (`ID_PERSONA` )
    REFERENCES `PERSONAS` (`ID_PERSONA` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ALUMNOS_ID_CLASE`
    FOREIGN KEY (`ID_CLASE` )
    REFERENCES `CLASES` (`ID_CLASE` )
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_ALUMNOS_ID_PERSONA` ON `ALUMNOS` (`ID_PERSONA` ASC) ;

CREATE INDEX `FK_ALUMNOS_ID_CLASE` ON `ALUMNOS` (`ID_CLASE` ASC) ;


-- -----------------------------------------------------
-- Table `CALIFICACIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CALIFICACIONES` ;

CREATE  TABLE IF NOT EXISTS `CALIFICACIONES` (
  `ID_CALIFICACION` BIGINT(20) NOT NULL AUTO_INCREMENT ,
  `FECHA` DATETIME NOT NULL ,
  `MODULO` VARCHAR(255) NULL DEFAULT NULL ,
  `NOTA` FLOAT NOT NULL ,
  `ID_ALUMNO` BIGINT(20) NULL DEFAULT NULL ,
  PRIMARY KEY (`ID_CALIFICACION`) ,
  CONSTRAINT `FK_CALIFICACIONES_ID_ALUMNO`
    FOREIGN KEY (`ID_ALUMNO` )
    REFERENCES `ALUMNOS` (`ID_PERSONA` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_CALIFICACIONES_ID_ALUMNO` ON `CALIFICACIONES` (`ID_ALUMNO` ASC) ;


-- -----------------------------------------------------
-- Table `PROFESORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROFESORES` ;

CREATE  TABLE IF NOT EXISTS `PROFESORES` (
  `ID_PERSONA` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`ID_PERSONA`) ,
  CONSTRAINT `FK_PROFESORES_ID_PERSONA`
    FOREIGN KEY (`ID_PERSONA` )
    REFERENCES `PERSONAS` (`ID_PERSONA` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_PROFESORES_ID_PERSONA` ON `PROFESORES` (`ID_PERSONA` ASC) ;


-- -----------------------------------------------------
-- Table `PROFESORES_CLASE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROFESORES_CLASE` ;

CREATE  TABLE IF NOT EXISTS `PROFESORES_CLASE` (
  `ID_PROFESOR` BIGINT(20) NOT NULL ,
  `ID_CLASE` BIGINT(20) NOT NULL ,
  PRIMARY KEY (`ID_PROFESOR`, `ID_CLASE`) ,
  CONSTRAINT `FK_PROFESORES_CLASE_ID_PERSONA`
    FOREIGN KEY (`ID_PROFESOR` )
    REFERENCES `PROFESORES` (`ID_PERSONA` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROFESORES_CLASE_ID_CLASE`
    FOREIGN KEY (`ID_CLASE` )
    REFERENCES `CLASES` (`ID_CLASE` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `FK_PROFESORES_CLASE_ID_PERSONA` ON `PROFESORES_CLASE` (`ID_PROFESOR` ASC) ;

CREATE INDEX `FK_PROFESORES_CLASE_ID_CLASE` ON `PROFESORES_CLASE` (`ID_CLASE` ASC) ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
